import Head from "next/head";
import { Inter } from "next/font/google";
import Hero from "@/components/home/Hero";
import { Container } from "@/layouts/Container";
import CardList from "@/components/card/CardList";

import { ArticleProps, Category } from "@/type";
import { sanityClient } from "@/components/studio/client";
import Meta from "@/components/Meta";
interface HomeProps {
  articles: ArticleProps[];
  categories: Category[];
}

const query = `{
  "articles":*[_type == "blog"]{
  title,
    slug,
    _id,
    _type,
    body,
    author->{
      name
    }
},
  "categories":*[_type=="category"]
}`;
export default function Home(props: HomeProps) {
  const { articles } = props;
  console.log(articles, "it is not array");
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Container>
          <Meta
            meta={{
              title: "Home| Zaw Z Tun",
              image: "/zzt.jpeg",
              description:
                "I am currently a Freelence Web Developer. My background is Cisco certified Network Engineer.",
            }}
          ></Meta>
          <Hero />
          <CardList blogs={articles} />
        </Container>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const data = await sanityClient.fetch(query);
  console.log(data);
  return {
    props: {
      ...data,
    },
  };
}
