import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import AllPosts from "@/components/allposts/AllPosts";

import Hero from "@/components/home/Hero";
import CardList from "@/components/card/CardList";
import Footer from "@/components/footer/Footer";
import { Container } from "@/layouts/Container";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Container>
          <Hero />
          <CardList />
        </Container>
      </div>
    </>
  );
}
